### ISSUE TITLE
Warn user that they need to add an environment variable after installing elm-script

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-script#16]
I ran `deno install -A -n elm-script ~/elm-script/runner/main.js` and thought I was done but when I tried to then run `elm-script run GetCurrentTime.elm` it didn't work. Turns out I didn't read the output clearly and the last part here isn't a notice that a path has been added but instructions that you need to add this to path.
```
✅ Successfully installed elm-script
/Users/martinstewart/.deno/bin/elm-script
ℹ️  Add /Users/martinstewart/.deno/bin to PATH
    export PATH="/Users/martinstewart/.deno/bin:$PATH"
```

I think it would be a good idea for the readme to mention that you need to add `/Users/martinstewart/.deno/bin:` to the path env variable.

**Comment by ianmackenzie** [comment]
Good point, I just tweaked the README to mention the PATH issue and point to the `deno install` docs - I'm a bit reluctant to add specific instructions like adding `$HOME/.deno/bin` to the path since that's OS-specific and seems to duplicate the Deno docs themselves. Hopefully this is a decent compromise!
