### ISSUE TITLE
Script with module name in the form of Module.SubModule won't run

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-script#20]
If I try running something like `Scripts.ListPackages` it will fail with
```
 % elm-script run ListPackages.elm
error: Uncaught TypeError: program.init is not a function
  program.init({ flags: flags });
          ^
    at runCompiledJs (file:///Users/martinstewart/elm-script/runner/main.js:126:11)
    at main (file:///Users/martinstewart/elm-script/runner/main.js:412:9)
```
Note that if I instead try `elm-script run Scripts.ListPackages.elm`, I will get an error saying it can't find the file.

Lastly, if I rename the module from `Scripts.ListPackages` to `ListPackages`, it works.

**Comment by ianmackenzie** [comment]
Oof, good catch, sorry about that! Looks like the logic [here](https://github.com/ianmackenzie/elm-script/blob/b24c2156d191a5daacb2893b81879d3036e44a05/runner/main.js#L115) will need to be improved, since it doesn't account for the possibility of nested module names under the global `Elm` object. Maybe something like a recursive function that looks for either an `init` function in the current module or a single nested module to recurse into...

**Comment by ianmackenzie** [comment]
It's also possible that at the same time that could be made more flexible with an optional `--program/-p` argument to `elm-script run`, so that if you _did_ have multiple Elm programs compiled into a single JavaScript file then you could do something like

```
elm-script run -p My.Nested.Program compiled.js
```

**Comment by ianmackenzie** [comment]
What advantage would that give over just passing the file path? I think passing the file path has several advantages:

- Consistent with how most other scripting languages I can think of (Python, JavaScript, Ruby etc.) work
- Allows running of scripts from outside the Elm project they're in
- Lets the Elm compiler handle parsing `elm.json` etc. (avoid needing to re-implement logic like walking up the directory tree to find a parent `elm.json`, map module name to file name efficiently, check for errors like duplicate module names in different source directories, etc.)

**Comment by MartinSStewart** [comment]
Good points. I think I'm misunderstanding your example then. `elm-script run -p My.Nested.Program compiled.js` Here, why is compiled.js needed? I thought elm-script was responsible for automatically building the js file and then running it?

**Comment by ianmackenzie** [comment]
Currently `elm-script` supports either running a .elm file directly (in which case yes, `elm-script` will call `elm make` behind the scenes) _or_ running an already-compiled .js file. The latter is less common, but I figured it would be useful in some cases like if you wanted to do something like

```
elm make --optimize MyScript.elm --output=/path/to/my_script.js
alias my_script="elm-script run /path/to/my_script.js"
```

which would avoid the (small) overhead of running `elm make` every time you call `my_script`. My idea of having `-p/--program` could then potentially be useful if you had pre-compiled several different Elm modules into a single JavaScript file and wanted to run a specific one of them.

BTW, running a compiled .js file directly is also currently a workaround if you want to run an Elm file that has `Debug` calls, since `elm-script` will by default invoke `elm make --optimize`; at some point I should probably add a `--debug` option to `elm-script` which will then cause `elm make` to be invoked without `--optimize`.

**Comment by MartinSStewart** [comment]
Yeah, a debug flag will be nice to have. I needed to debug my script and it was awkward trying to move around code so I could use `printLine`.
